version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: food_delivery_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
