"""add is_admin to user

Revision ID: 57c52a749237
Revises: 41c50e7c8d60
Create Date: 2026-02-11 22:09:22.196665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c52a749237'
down_revision: Union[str, Sequence[str], None] = '41c50e7c8d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("is_admin", sa.Boolean(), nullable=True),
    )
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    op.alter_column("users", "is_admin", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
