"""add completed_at to orders and order_id for notification

Revision ID: 9559afc38fa3
Revises: 57c52a749237
Create Date: 2026-02-17 19:40:16.930200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9559afc38fa3'
down_revision: Union[str, Sequence[str], None] = '57c52a749237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_order_id'), 'notifications', ['order_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'orders', ['order_id'], ['id'])
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'completed_at')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_order_id'), table_name='notifications')
    op.drop_column('notifications', 'order_id')
    # ### end Alembic commands ###
