"""updated User and created PendingUser

Revision ID: a67dd438678e
Revises: e6331956f565
Create Date: 2025-09-05 21:52:15.396044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67dd438678e'
down_revision: Union[str, Sequence[str], None] = 'e6331956f565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_users_id'), 'pending_users', ['id'], unique=False)
    op.create_index(op.f('ix_pending_users_phone'), 'pending_users', ['phone'], unique=True)
    op.create_index(op.f('ix_pending_users_session_id'), 'pending_users', ['session_id'], unique=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_pending_users_session_id'), table_name='pending_users')
    op.drop_index(op.f('ix_pending_users_phone'), table_name='pending_users')
    op.drop_index(op.f('ix_pending_users_id'), table_name='pending_users')
    op.drop_table('pending_users')
    # ### end Alembic commands ###
